datagrids:
    video-section-grid:
        extended_entity_name: 'Oro\Bundle\WebCatalogBundle\Entity\ContentNode'
        options:
            frontend: true
            entity_pagination: true
            toolbarOptions:
                placement:
                    top: false
                pageSize:
                    items: [10]
                    default_per_page: 10
        source:
            skip_acl_apply: true
            type: orm
            query:
                select:
                    - partial variant.{ id, node }
                    - video.shortDescription
                    - video.link
                from:
                    - { table: Oro\Bundle\WebCatalogBundle\Entity\ContentVariant, alias: variant }
                join:
                    left:
                        - { join: variant.video, alias: video }
                        - { join: variant.node, alias: node }
                where:
                    and:
                        - variant.type = 'Oro\Bundle\ResourceLibraryBundle\ContentVariantType\VideoListSectionItemContentVariantType::TYPE'
                        - video.id IS NOT NULL
                        - IDENTITY(node.parentNode) = :contentNodeId
                        - variant.id IN (:variantIds)
                orderBy:
                      - column: video.createdAt
                        dir: desc
            bind_parameters:
                -
                    name: contentNodeId
                -
                    name: variantIds
        columns:
            video:
                type: twig
                frontend_type: html
                template: '@OroResourceLibrary/Video/Datagrid/Property/video.html.twig'
            data:
                type: twig
                frontend_type: html
                template: '@OroResourceLibrary/Video/Datagrid/Property/data.html.twig'

    news-announcements-article-grid:
        extended_entity_name: 'Oro\Bundle\WebCatalogBundle\Entity\ContentVariant'
        options:
            frontend: true
            entity_pagination: true
            toolbarOptions:
                placement:
                    top: false
                pageSize:
                    items: [10]
                    default_per_page: 10
        source:
            type: orm
            skip_acl_apply: true
            query:
                select:
                    - node
                    - variant
                    - article
                    - image
                from:
                    - { table: Oro\Bundle\WebCatalogBundle\Entity\ContentVariant, alias: variant }
                join:
                    inner:
                        - { join: variant.node, alias: node }
                        - { join: variant.news_announcements_article, alias: article }
                    left:
                        - { join: article.image, alias: image }
                where:
                    and:
                        - variant.id IN (:variantIds)
                        - article.createdAt < :today
                orderBy:
                    - column: article.createdAt
                      dir: desc
            bind_parameters:
                - variantIds
                - today
        properties:
            parentNodeId: ~
        columns:
            node:
                type: twig
                frontend_type: html
                template: '@OroResourceLibrary/NewsAnnouncements/Datagrid/Property/news_announcements_article.html.twig'
