Oro\Bundle\ResourceLibraryBundle\Entity\Video:
    properties:
        shortDescription:
            - NotBlank: ~
        description:
            - NotBlank: ~
        link:
            - NotBlank: ~
            - Length:
                min: 1
                max: 255
            - Url: ~
            - Oro\Bundle\SecurityBundle\Validator\Constraints\NotDangerousProtocol:
                message: oro.resourcelibrary.video.url.not_dangerous_protocol.message
            - Regex:
                  pattern: '~^(http|https)://youtu.be/[^/]+$~'
                  message: oro.resourcelibrary.video.url.youtube_link.message
Oro\Bundle\ResourceLibraryBundle\Entity\MediaKit:
    properties:
        description:
            - NotBlank: ~
        link:
            - NotBlank: ~
            - Length:
                min: 1
                max: 255
            - Url: ~
            - Oro\Bundle\SecurityBundle\Validator\Constraints\NotDangerousProtocol:
                  message: oro.resourcelibrary.mediakit.url.not_dangerous_protocol.message
        banner:
            - NotBlank: ~
        media_kit_file:
            - NotBlank: ~

Oro\Bundle\ResourceLibraryBundle\Entity\NewsAnnouncementsArticle:
    properties:
        shortDescription:
            - NotBlank: ~
        description:
            - NotBlank: ~
